// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RealtimeConversationAudioChunk } from "./RealtimeConversationAudioChunk";

export type RealtimeConversationOutputAudioDeltaNotification = { threadId: string, audio: RealtimeConversationAudioChunk, };
